#!/bin/bash
#SCBATH --job-name=snk-chinook
#SBATCH --output=snk-chinook.txt

#SBATCH --mail-user=clazari@ucsc.edu
#SBATCH --mail-type=ALL
#SBATCH -p 128x24
#SBATCH -t 10:00:00
#SBATCH --nodes=all
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=48G

##commands to run

module load samtools
module load bcftools
module load bwa-mem2
snakemake --unlock
snakemake -p results/vcf/all.vcf.gz --rerun-incomplete --cores 2

