#!/bin/bash
#SCBATH --job-name=snk-chinook
#SBATCH --output=snk-chinook.txt

#SBATCH --mail-user=carolina.lazari@noaa.gov
#SBATCH --mail-type=ALL
#SBATCH -p standard
#SBATCH -t 10:00:00
#SBATCH --nodes=2
#SBATCH --cpus-per-task=2
#SBATCH --mem=10G

##commands to run

module load bio/samtools
module load bio/bcftools
module load aligners/bwa-mem2
snakemake --unlock
snakemake -p results/vcf/all.vcf.gz --rerun-incomplete --cores 2

