
# path to the genome (not used in workflow, but we could have...)
genome_path: "Reference/ncbi_dataset/data/GCF_018296145.1/GCF_018296145.1_Otsh_v2.0_genomic.fna"

# path to file with information about samples
sample_info: "Snakemake/config/units_run1.tsv"

# Put the list of chromosomes we want to do here
#for the first run I just included some of them
chromos: 
  - "NC_056429.1"
  - "NC_056430.1"
  - "NC_056431.1"
  - "NC_056432.1"
 

# parameters to be used for different rules/programs
params:
  fastp:
    adapter_sequence1: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
    adapter_sequence2: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
    other_options:
      - "--detect_adapter_for_pe"
      - "--cut_right" 
      - "--cut_right_window_size 4"
      - "--cut_right_mean_quality 20"
  gatk:
    HaplotypeCaller:
      hmm_threads: 1

    
